require('plugins/config/lsp')
require('plugins/config/cmp')
require('plugins/config/treesitter')
require('plugins/config/luatab')
require('plugins/config/nvimtree')
require('plugins/config/lualine')
require('plugins/config/codeactionmenu')
require('plugins/config/registers')
require('plugins/config/vista')
-- require('plugins/config/bufferline')
require('plugins/config/git')
require('plugins/config/jabs')
